### ISSUE TITLE
No option for slot cancellation

### ISSUE THREAD

**Issue by RushikeshChary** [aleph-7/elysium#3]
There is no option for cancellation of any slot booked on the website. It is possible that the user wants to change his plans later. So I think a cancellation policy is necessary.

**Comment by whizdor** [comment]
Please refer to the user manual/ implementation document. The entire reasoning behind pre-booking to be open only for a day in advanced is that the user has his plans thought out. The algorithm applies a penalty for a no show, in order to ensure maximum utilisation of the resources.
